### ISSUE TITLE
AltiVec/VMX instructions override Gekko PS_* instructions

### ISSUE THREAD

**Issue by shiiion** [yui-konnu/PPC-Altivec-IDA#2]
Because of the support for 3 separate extensions, the Gekko support is effectively bunk. ps_add, ps_mul, etc are overriden by whichever AltiVec/VMX instruction matches first. 

Also the W operand has the incorrect shift, should be 15, not 16.

**Comment by hayleyxyz** [comment]
I only really have knowledge of the Xenon instructions/sprgs; Gekko and CELL have fallen by the wayside. If you are able to submit a PR with those changes, I will happily merge.
